export const UnknownEscapeChar = Error('unknown escape char')
export const UnknownKeyword = Error('unknown keyword')
export const MissingSquareBracketClosing = Error('missing square bracket closing')
export const MissingBraceClosing = Error('missing brace closing')
export const ExpectBraceStarting = Error('missing brace closing')